# Python program to find the greatest of two numbers using the built-in function
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))
num4 = int(input("Enter the fourth number: "))
num5 = int(input("Enter the fivth number: "))
num6 = int(input("Enter the sixth number: "))
num7 = int(input("Enter the sixth number: "))
num8 = int(input("Enter the eighth number: "))
num9 = int(input("Enter the nineth number: "))
num10 = int(input("Enter the tanth number: "))
print(max(num1, num2, num3,num4, num5, num6, num7, num8, num9, num10), "is greater")
print("Rest of the code")
